spring.application.name=reactthreeproject

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.static-locations=file:build
spring.web.resources.cache.period=0

spring.web.resources.cache.cachecontrol.max-age=1
spring.web.resources.cache.cachecontrol.must-revalidate=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.jackson.time-zone=UTC

management.endpoints.web.exposure.include=*

server.port=${PORT:8080}